<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace>toggle_lang</RootNamespace>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>assets\icon.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="assets\icon.ico" />
    <Resource Include="assets\icon.png" />
    <None Include="assets\icon.ico" CopyToOutputDirectory="PreserveNewest" />
    <None Include="assets\icon.png" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>

